In [1]:
import pandas as pd 

# import data

In [2]:
data=pd.read_csv("C:\\Users\\welcome\\company task\\Precily Assessment\\Text_Similarity_Dataset.csv")

In [3]:
data.head(7)

Unique_ID                                              text1  \
0          0  savvy searchers fail to spot ads internet sear...   
1          1  millions to miss out on the net by 2025  40% o...   
2          2  young debut cut short by ginepri fifteen-year-...   
3          3  diageo to buy us wine firm diageo  the world s...   
4          4  be careful how you code a new european directi...   
5          5  india seeks to boost construction india has cl...   
6          6  podcasters  look to net money nasa is doing it...   

                                               text2  
0  newcastle 2-1 bolton kieron dyer smashed home ...  
1  nasdaq planning $100m share sale the owner of ...  
2  ruddock backs yapp s credentials wales coach m...  
3  mci shares climb on takeover bid shares in us ...  
4  media gadgets get moving pocket-sized devices ...  
5  music mogul fuller sells company pop idol supr...  
6  ukip outspent labour on eu poll the uk indepen...

In [4]:
data.shape

(4023, 3)

# you can also create word to vector through this word embedding

In [5]:
from gensim.models import Word2Vec

In [6]:
data["text1"].shape

(4023,)

# word_tokenize to split data into words

In [7]:
from nltk.tokenize import word_tokenize

In [8]:
data["text2"].shape

(4023,)

# cosine similarity for getting value inbetween  0 and 1 ,compare data and tells how your text is similar or dissimilar

In [9]:
from sklearn.metrics.pairwise import cosine_similarity
from nltk.stem  import WordNetLemmatizer


# word lemmatize is for grammatical errorcorrection

In [10]:
from nltk.corpus import stopwords
import string
import re
stop_words=stopwords.words('english')
ss=WordNetLemmatizer()

# clean data or text data

In [11]:

def clean_data(text):
    #it is used to replace this term re.sub(pattern,replace,string)
    
    text = re.sub('<[^>]*>', '', text)
    #it is used to find all the matches and remove emoji
    emoticons = re.findall('(?::|;|=)(?:-)',text)
    #replace punctuation 
    text = (re.sub('[\W]+', ' ', text.lower()) +
            ' '.join(emoticons).replace('-', ''))
    rm_words = [w for w in text.split() if w.lower() not in stop_words]
    return ' '.join(rm_words)
    return text

In [12]:
data["text1"]=data["text1"].apply(clean_data)

In [13]:
data["text2"]=data["text2"].apply(clean_data)

In [14]:
data

Unique_ID                                              text1  \
0             0  savvy searchers fail spot ads internet search ...   
1             1  millions miss net 2025 40 uk population still ...   
2             2  young debut cut short ginepri fifteen year old...   
3             3  diageo buy us wine firm diageo world biggest s...   
4             4  careful code new european directive could put ...   
...         ...                                                ...   
4018       4018  labour plans maternity pay rise maternity pay ...   
4019       4019  high fuel costs hit us airlines two largest ai...   
4020       4020  britons growing digitally obese gadget lovers ...   
4021       4021  holmes hit hamstring injury kelly holmes force...   
4022       4022  nuclear dumpsite plan attacked plans allow for...   

                                                  text2  
0     newcastle 2 1 bolton kieron dyer smashed home ...  
1     nasdaq planning 100m share sale owner technolo...  
2     ruddock backs yapp credentials wales coach mik...  
3     mci shares climb takeover bid shares us phone ...  
4     media gadgets get moving pocket sized devices ...  
...                                                 ...  
4018  seasonal lift house market swathe figures prov...  
4019  new media battle bafta awards bbc leads nomina...  
4020  film star fox behind theatre bid leading actor...  
4021  tsunami hit sri lanka banks sri lanka banks fa...  
4022  x factor show gets second series tv talent sho...  

[4023 rows x 3 columns]

# vectorizer is for term frequency number of unique doc/text word occurs

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [16]:
tf_vectorizer=TfidfVectorizer()

# concat two text1 and text2

In [17]:
data["summary"]=data["text1"]+data["text2"]


In [18]:
#fit_transform is for on merge text because we cant fit two text because different vocab ,we want one vocab so that's why we merge two text

In [19]:
#here is to form document term matrix 
col1tf=tf_vectorizer.fit_transform(data["summary"])

# text1 for data

In [20]:
colt1=tf_vectorizer.transform(data["text1"]).toarray()

In [21]:
colt1

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.09942522, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [22]:
colt1.shape

(4023, 33251)

# text2 for data

In [23]:
#col2tf=tf_vectorizer.fit(data["text2"])

In [24]:
#here is to form document term matrix text2
colt2=tf_vectorizer.transform(data["text2"]).toarray()

In [25]:
colt2

array([[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       ...,
       [0.       , 0.0635813, 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.0299745, 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ]])

In [26]:
colt2[0]

array([0., 0., 0., ..., 0., 0., 0.])

# cosine similarity formula cosx=a.b/|a|.|b| will use this form in document term matrix of text1 and text2

In [27]:
cosine_similarity(colt1[0].reshape(1,-1),colt2[0].reshape(1,-1))

array([[0.0175394]])

In [28]:
#here we are predicting cosine angle with iteration in document term matrix to get prediction how much it is similar our text is to another text

# it will predict all element angle outer loop one text1 by every inner loop text2

In [29]:
#one text of text1 compare with every text2 sentence iteration and store in dictionary 
#dictonary helps me to find the max possible similar text will occurs in dictionary

# here we are parallel getting cosine angle

In [30]:
import itertools
import numpy as np

In [31]:
arr=[]
for i in range(len(colt1)):
    angle=cosine_similarity(colt1[i].reshape(1,-1),colt2[i].reshape(1,-1))
    arr.append(angle[0])
print(arr)
        

[array([0.0175394]), array([0.0263173]), array([0.03195371]), array([0.02206092]), array([0.05347863]), array([0.02937796]), array([0.02167619]), array([0.11252247]), array([0.05984806]), array([0.08424955]), array([0.00252675]), array([0.01225498]), array([0.02101925]), array([0.05833605]), array([0.14059727]), array([0.01142845]), array([0.01549406]), array([0.02518752]), array([0.17843197]), array([0.03356065]), array([0.0215436]), array([0.02429947]), array([0.02181627]), array([0.01528766]), array([0.0180303]), array([0.03438521]), array([0.01726117]), array([0.17316463]), array([0.02549731]), array([0.01740658]), array([0.01817948]), array([0.00323317]), array([0.07093043]), array([0.02624376]), array([0.0135833]), array([0.01347777]), array([0.02822635]), array([0.02432018]), array([0.02869707]), array([0.03582797]), array([0.02444024]), array([0.01960815]), array([0.032047]), array([0.03875161]), array([0.01805162]), array([0.07371953]), array([0.02672544]), array([0.01176263])

In [32]:
similarity_score=pd.DataFrame(arr)

In [33]:
similarity_score

0
0     0.017539
1     0.026317
2     0.031954
3     0.022061
4     0.053479
...        ...
4018  0.021932
4019  0.025142
4020  0.029272
4021  0.009442
4022  0.007236

[4023 rows x 1 columns]

In [34]:
data["similarity_score"]=similarity_score

In [35]:
data

Unique_ID                                              text1  \
0             0  savvy searchers fail spot ads internet search ...   
1             1  millions miss net 2025 40 uk population still ...   
2             2  young debut cut short ginepri fifteen year old...   
3             3  diageo buy us wine firm diageo world biggest s...   
4             4  careful code new european directive could put ...   
...         ...                                                ...   
4018       4018  labour plans maternity pay rise maternity pay ...   
4019       4019  high fuel costs hit us airlines two largest ai...   
4020       4020  britons growing digitally obese gadget lovers ...   
4021       4021  holmes hit hamstring injury kelly holmes force...   
4022       4022  nuclear dumpsite plan attacked plans allow for...   

                                                  text2  \
0     newcastle 2 1 bolton kieron dyer smashed home ...   
1     nasdaq planning 100m share sale owner technolo...   
2     ruddock backs yapp credentials wales coach mik...   
3     mci shares climb takeover bid shares us phone ...   
4     media gadgets get moving pocket sized devices ...   
...                                                 ...   
4018  seasonal lift house market swathe figures prov...   
4019  new media battle bafta awards bbc leads nomina...   
4020  film star fox behind theatre bid leading actor...   
4021  tsunami hit sri lanka banks sri lanka banks fa...   
4022  x factor show gets second series tv talent sho...   

                                                summary  similarity_score  
0     savvy searchers fail spot ads internet search ...          0.017539  
1     millions miss net 2025 40 uk population still ...          0.026317  
2     young debut cut short ginepri fifteen year old...          0.031954  
3     diageo buy us wine firm diageo world biggest s...          0.022061  
4     careful code new european directive could put ...          0.053479  
...                                                 ...               ...  
4018  labour plans maternity pay rise maternity pay ...          0.021932  
4019  high fuel costs hit us airlines two largest ai...          0.025142  
4020  britons growing digitally obese gadget lovers ...          0.029272  
4021  holmes hit hamstring injury kelly holmes force...          0.009442  
4022  nuclear dumpsite plan attacked plans allow for...          0.007236  

[4023 rows x 5 columns]

In [36]:
data.drop("summary",axis=1,inplace=True)

In [37]:
data.drop(["text1","text2"],axis=1,inplace=True)

In [38]:
data

Unique_ID  similarity_score
0             0          0.017539
1             1          0.026317
2             2          0.031954
3             3          0.022061
4             4          0.053479
...         ...               ...
4018       4018          0.021932
4019       4019          0.025142
4020       4020          0.029272
4021       4021          0.009442
4022       4022          0.007236

[4023 rows x 2 columns]

In [39]:
data.to_csv("Text_Similarityscore.csv")